
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
include: ['_pages', '_data']
-scope:
path: ""
values:
  layout: default
  _options:
    content: &content_defaults
      uploads_dir: "uploads/:title"
      format: p h1 h2 h3 h4 h5 h6 div
      styles: /assets/css/theme.css
      undo: true
      redo: true
      left: text-left
      center: text-center
      right: text-right
      justify: justify-content-center
      bold: true
      italic: true
      underline: true
      strike: true
      subscript: false
      superscript: false
      blockquote: true
      table: true
      copyformatting: true
      removeformat: true
      numberedlist: true
      bulletedlist: true
      outdent: false
      indent: false
      image: true
      link: true
      embed: true
-scope:
      type: pages
      path: _pages/index.html
      values:
        permalink: /

# Build settings
        # Permalinks
        permalink: /:title
        
        # Sass
        sass:
          sass_dir: _sass
          style: compressed
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
