site_title: "McCormick Law Firm"
site_description: >-
  "Shane McCormick has over 20 years of legal experience fighting for diverse clients. As a veteran, he knows the importance of persistence and determination. He brings all these valuable skills to the courtroom to ensure the best possible outcome for every client, every time. A local attorney who knows the system, he has been providing outstanding legal services to Acadiana and the surrounding area since 2002."

site_logo_url: "/assets/images/white_logo.png"
page_logo_url: "/assets/images/logo.png"
footer_logo_url: "/assets/images/footer_logo.png"

phone: "337-889-0529"
email: "contact@mccormickaplc.com"
contact_form_action_url: "https://formsubmit.io/send/rubel2585@gmail.com"
address: "503 W UNIVERSITY AVE LAFAYETTE, LA 70506"
google_map_url: "https://goo.gl/maps/wGeyTHv8BYe9CGGt5"
footer_title: "VETERAN OWNED<br/> 20 YEARS EXPERIENCE"

social_accounts:
  - url: "https://www.facebook.com/McCormick-Law-Firm-and-R-Shane-McCormick-1602968356585620"
    icon: "/assets/images/fb_icon.png"

ga_id: UA-12345678-1
head_code: ''
body_code: ''
footer_code: ''











                

